<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="connectedFamily" nsURI="http://www.example.org/connectedFamily"
    nsPrefix="connectedFamily">
  <eClassifiers xsi:type="ecore:EClass" name="Country">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cities" upperBound="-1"
        eType="#//City" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routers" upperBound="-1"
        eType="#//WideRouter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="City">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="families" upperBound="-1"
        eType="#//Family" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routers" upperBound="-1"
        eType="#//MetropolitanRouter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Family">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Person" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routers" upperBound="-1"
        eType="#//LocalRouter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Woman" eSuperTypes="#//Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="Man" eSuperTypes="#//Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="Router" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalRouter" eSuperTypes="#//Router">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superRouter" eType="#//MetropolitanRouter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetropolitanRouter" eSuperTypes="#//Router">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superRouter" eType="#//WideRouter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectedRouters" upperBound="-1"
        eType="#//LocalRouter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WideRouter" eSuperTypes="#//Router">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectedRouters" upperBound="-1"
        eType="#//MetropolitanRouter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="siblings" upperBound="-1"
        eType="#//WideRouter"/>
  </eClassifiers>
</ecore:EPackage>
